### ISSUE TITLE
No such file or directory: '/usr/lib/python3.6/site-packages/flashfocus/default_config.yml

### ISSUE THREAD

**Issue by indeedwatson** [fennerm/flashfocus#14]
Full trace:

```python
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 8, in <module>
    from flashfocus.ui import cli
  File "/usr/lib/python3.6/site-packages/flashfocus/ui.py", line 18, in <module>
    from flashfocus.config import (
  File "/usr/lib/python3.6/site-packages/flashfocus/config.py", line 199, in <module>
    default_config=load_config(DEFAULT_CONFIG_FILE),
  File "/usr/lib/python3.6/site-packages/flashfocus/config.py", line 125, in load_config
    with open(str(config_file), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/flashfocus/default_config.yml'
```

This started happening about a week ago. I have the config file in `~/.config/flashfocus/flashfocus.yml`, but there is no `default_config.yml` in the `/usr/lib/python3.6/site-packages/flashfocus` folder.

**Comment by fennerm** [comment]
This should have been fixed in the latest update. Could you do a reinstall and report back?

**Comment by indeedwatson** [comment]
I've tried reinstalling, even uninstalling and installing again (from AUR).

**Comment by fennerm** [comment]
Weird, I routinely clean reinstall from the AUR and it works fine for me. My guess is that there is something weird going on with caching. What is the output of `pip show flashfocus`?

 As a stopgap, maybe just copy the file from the git repo to the correct location.

**Comment by indeedwatson** [comment]
```python
Name: flashfocus
Version: 1.0.4
Summary: Simple focus animations for tiling window managers
Home-page: https://www.github.com/fennerm/flashfocus
Author: Fenner Macrae
Author-email: fmacrae.dev@gmail.com
License: MIT
Location: /usr/lib/python3.6/site-packages
Requires: xcffib, click, cffi, xpybutil, marshmallow, pyyaml
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by indeedwatson** [comment]
Indeed it is! Good job.
