### ISSUE TITLE
error on empty focus

### ISSUE THREAD

**Issue by 9too** [fennerm/flashfocus#15]
I use **dwm** and when I select an empty tag flashfocus logs an error and continues, but it stops animating and only log `INFO: Focus shifted...`.

## Log
```
INFO: Focus shifted...
Traceback (most recent call last):
  File "/home/gtoo/.local/bin/flashfocus", line 11, in <module>
    sys.exit(cli())
  File "/home/gtoo/.local/lib64/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/ui.py", line 80, in cli
    init_server(kwargs)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/ui.py", line 101, in init_server
    return server.event_loop()
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/server.py", line 97, in event_loop
    self._flash_queued_window()
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/server.py", line 121, in _flash_queued_window
    self.matcher.direct_request(window, request_type)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/rule.py", line 93, in direct_request
    flasher = self.match(window, request_type)[1]
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/rule.py", line 119, in match
    window_id, window_class = get_wm_class(window)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/flashfocus/xutil.py", line 45, in get_wm_class
    xpybutil.util.get_property(window, 'WM_CLASS').reply())
  File "/home/gtoo/.local/lib64/python3.5/site-packages/xpybutil/util.py", line 117, in get_property
    2 ** 32 - 1)
  File "/home/gtoo/.local/lib64/python3.5/site-packages/xcffib/xproto.py", line 2719, in GetProperty
    buf.write(struct.pack("=xB2xIIIII", delete, window, property, type, long_offset, long_length))
struct.error: required argument is not an integer
```

**Comment by fennerm** [comment]
Thanks for the report! This looks like it should be a relatively easy fix. I'm away from computer today but I'll try to push a patch tomorrow.

**Comment by 9too** [comment]
I made a quick fix for the version 1.0.0 that I have installed : 
```
def get_wm_class(window):
    """Get the ID and class of a window

    Returns
    -------
    Tuple[str, str]
        (window id, window class)

    """
    reply = ["",""]
    if window:
        reply = xpybutil.util.get_property_value(
            xpybutil.util.get_property(window, 'WM_CLASS').reply())
    return reply[0], reply[1]
```

The problem is that `window == None`.

I see there is a tagged version 1.0.5 but it's not available on [PyPI](https://pypi.org/project/flashfocus/#history). I noticed some code change on this function but I think the problem would still occur on version 1.0.5

**Comment by 9too** [comment]
Actually nevemind that, I ran v1.0.5 and the problem doesn't occur !

**Comment by fennerm** [comment]
Glad you got it figured out ^^
