### ISSUE TITLE
Error when initializing with no windows

### ISSUE THREAD

**Issue by aouerfelli** [fennerm/flashfocus#23]
I am using bspwm, so after adding the line `flashfocus &` to my `bspwmrc`, I get the following relevant log from `startx`:
```py
INFO: Setting all windows to their default opacity...
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flashfocus/ui.py", line 124, in cli
    init_server(kwargs)
  File "/usr/lib/python3.7/site-packages/flashfocus/ui.py", line 145, in init_server
    return server.event_loop()
  File "/usr/lib/python3.7/site-packages/flashfocus/server.py", line 109, in event_loop
    self._set_all_window_opacity_to_default()
  File "/usr/lib/python3.7/site-packages/flashfocus/server.py", line 152, in _set_all_window_opacity_to_default
    for window in list_mapped_windows():
TypeError: 'NoneType' object is not iterable
```
Running it manually in bspwm works as expected.

**Comment by fennerm** [comment]
Sorry accidentally closed. I just pushed a fix to master, could you reinstall and let me know if the issue i s solved for you?

**Comment by aouerfelli** [comment]
Yep, it works great now. Thanks!
