### ISSUE TITLE
Can't launch flashfocus

### ISSUE THREAD

**Issue by Phaenyxx** [fennerm/flashfocus#26]
Fedora 29, installed the ubuntu-listed packages with the exception of ``libxcb-render0-dev`` (couldn't find the replacement, it may be the problem), got this error at launch : 
```
/usr/local/lib/python3.7/site-packages/flashfocus-1.2.1-py3.7.egg/flashfocus/config.py:138: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
INFO: Loading configuration from {'flash_opacity': 0.8, 'default_opacity': 1, 'time': 500, 'simple': False, 'ntimepoints': 10, 'flash_on_focus': True, 'flash_lone_windows': 'always'}
Traceback (most recent call last):
  File "/usr/local/bin/flashfocus", line 12, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flashfocus-1.2.1-py3.7.egg/flashfocus/ui.py", line 120, in cli
    init_server(kwargs)
  File "/usr/local/lib/python3.7/site-packages/flashfocus-1.2.1-py3.7.egg/flashfocus/ui.py", line 134, in init_server
    config = load_merged_config(cli_options)
  File "/usr/local/lib/python3.7/site-packages/flashfocus-1.2.1-py3.7.egg/flashfocus/config.py", line 288, in load_merged_config
    config = merge_config_sources(cli_options, user_config, default_config)
  File "/usr/local/lib/python3.7/site-packages/flashfocus-1.2.1-py3.7.egg/flashfocus/config.py", line 230, in merge_config_sources
    validated_config = validate_config(config)
  File "/usr/local/lib/python3.7/site-packages/flashfocus-1.2.1-py3.7.egg/flashfocus/config.py", line 192, in validate_config
    validated = ConfigSchema(strict=True).load(config)
TypeError: __init__() got an unexpected keyword argument 'strict'
```

**Comment by fennerm** [comment]
Ah looks like you have a prerelease of the marshmallow library installed. I thought I had prepared for this one but guess not. Just pushed a new version which I think should fix this for you (v.1.2.6)

**Comment by Phaenyxx** [comment]
Works like a charm, thank you very much. Should I close, or let you do it ?
