### ISSUE TITLE
Crashes when switching tags on dwm

### ISSUE THREAD

**Issue by eikaiwa-simons** [fennerm/flashfocus#39]
Crashes when switching tags and opening new windows in dwm.

INFO: Resetting window 27262981 opacity to default
INFO: Resetting window 25165829 opacity to default
INFO: Resetting window 23068677 opacity to default
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 208, in run
    self._handle_property_change(event)
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 236, in _handle_property_change
    focused_window = get_focused_window()
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 246, in get_focused_window
    return Window(get_active_window().reply())
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 69, in __init__
    raise WMError("Undefined window")
flashfocus.errors.WMError: Undefined window

**Comment by fennerm** [comment]
Thanks for reporting i’ll take a look this weekend

**Comment by fennerm** [comment]
This should be fixed in the latest release (2.1.0). Closing this but let me know if you have further issues.

**Comment by eikaiwa-simons** [comment]
It seems to still be an issue. Thank you for the attempt to fix it.

Exception in thread TException in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 217, in run
    self._handle_property_change(event)
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 247, in _handle_property_change
    logging.info(f"Focus shifted to {focused_window.id}")
AttributeError: 'NoneType' object has no attribute 'id'
hread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 217, in run
    self._handle_property_change(event)
  File "/usr/lib/python3.6/site-packages/flashfocus/display_protocols/x11.py", line 247, in _handle_property_change
    logging.info(f"Focus shifted to {focused_window.id}")
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by fennerm** [comment]
Just pushed a patch release, give it a try now. Sorry hard to test this since I don't have a dwm install set up.

**Comment by eikaiwa-simons** [comment]
Everything is working well! Thank you for taking the time to fix it

**Comment by fennerm** [comment]
nice!
