### ISSUE TITLE
Broken on marshmallow-3.4.0

### ISSUE THREAD

**Issue by travankor** [fennerm/flashfocus#44]
```
INFO: Loading configuration from /home/travankor/.config/flashfocus/flashfocus.yml
Traceback (most recent call last):
  File "/bin/flashfocus", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 91, in cli
    init_server(kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 105, in init_server
    config = load_merged_config(config_file_path=Path(config_file_path), cli_options=cli_options)
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 316, in load_merged_config
    config = merge_config_sources(
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 305, in merge_config_sources
    validated_config = validate_config(config)
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 214, in validate_config
    validated: Dict = schema.load(config).data
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 856, in _do_load
    result = self._deserialize(
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 493, in _call_and_store
    value = getter_func(data)
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/usr/lib/python3.8/site-packages/marshmallow/fields.py", line 343, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/usr/lib/python3.8/site-packages/marshmallow/fields.py", line 601, in _deserialize
    return self._load(value, data, partial=partial, many=many)
  File "/usr/lib/python3.8/site-packages/marshmallow/fields.py", line 582, in _load
    valid_data = self.schema.load(                                                                                     
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load                                     
    return self._do_load(                                                                                              
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 856, in _do_load                                 
    result = self._deserialize(                                                                                        
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 618, in _deserialize                             
    ret = [                                                                                                            
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 621, in <listcomp>                               
    self._deserialize(                                                                                                 
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 664, in _deserialize                             
    value = self._call_and_store(                                                                                      
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 493, in _call_and_store                          
    value = getter_func(data)                                                                                          
  File "/usr/lib/python3.8/site-packages/marshmallow/schema.py", line 661, in <lambda>                                 
    getter = lambda val: field_obj.deserialize(                                                                        
TypeError: deserialize() got an unexpected keyword argument 'partial'  
```

**Comment by travankor** [comment]
Sorry for this noise, I had the wrong version installed.
