### ISSUE TITLE
The 'pbr' distribution was not found and is required by tendo

### ISSUE THREAD

**Issue by Araly** [fennerm/flashfocus#7]
flashfocus is not working anymore in i3wm, I installed the flashfocus-git package from AUR.

When I launch `flashfocus` from the terminal I get : 
```Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pbr' distribution was not found and is required by tendo
```

**Comment by fennerm** [comment]
It looks like tendo might have an undeclared dependency. Try install `python-pbr`. If that doesn't work, I'm planning to push a big update to flashfocus later today or tomorrow in which the tendo dependency is removed so hold tight.

**Comment by fennerm** [comment]
Just pushed the update!  Give it another try and let me know how it goes.

**Comment by Araly** [comment]
Just updated, it works now, nice job !
