### ISSUE TITLE
Support needed: hyprland

### ISSUE THREAD

**Issue by Zeioth** [fennerm/flashfocus#81]
This is the error when running

    flashfocus

On hyprland

``` sh
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 8, in <module>
    from flashfocus.cli import cli
  File "/usr/lib/python3.10/site-packages/flashfocus/cli.py", line 11, in <module>
    from flashfocus.config import init_user_configfile, load_merged_config
  File "/usr/lib/python3.10/site-packages/flashfocus/config.py", line 21, in <module>
    from flashfocus.compat import DisplayProtocol, get_display_protocol
  File "/usr/lib/python3.10/site-packages/flashfocus/compat.py", line 40, in <module>
    raise UnsupportedWM("This window manager is not supported yet.")
flashfocus.errors.UnsupportedWM: This window manager is not supported yet.
```

**Comment by Artturin** [comment]
there's https://github.com/hyprland-community/hyprland-py but it doesn't support windowrules yet so support may be dependant on that (and someone who uses hyprland and wants to add support for it here)

**Comment by Zeioth** [comment]
It seems someone did an hyprland plugin of this too:
https://github.com/VortexCoyote/hyprfocus

**Comment by fennerm** [comment]
Yeah hyperland is not supported atm. Unfortunately support for each wayland wm needs to be implemented separately. Wasn't aware of hyprfocus, will add a linkout to it in the README when I get a moment :)
